language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

env:
 - PUPPET_VERSION=3.7.3

script: 'bundle exec rake'

notifications:
  email:
    on_failure: change
    on_success: never

addons:
  code_climate:
    repo_token: c47db3a4a7d96eb8a54354f5616502ae37a2bb07ece184395ea91fd5e22249a6
